### ISSUE TITLE
Repeat command n times

### ISSUE THREAD

**Issue by mewfree** [philc/sheetkeys#1]
Hey @philc, amazing work you've done here.

One of first things I tried after playing with the extension a little bit was use numbers to move around (`5j` to move down 5 rows for example), and after checking the code I quickly realized it wasn't implemented.

Would be really great to have that as a feature, in order to mimick Vim behaviour even closer. I might jump in and submit a pull request when I have some free time soon. Have you ever thought about this feature? Do you have any idea of how it could be implemented so that I can have some guidance if I want to try to do it myself? I'll check how this was implemented in Vimium.

Thanks!

**Comment by philc** [comment]
Hey Damien, it would be great to have support for repeat keys, and I'd
welcome a PR if you want to take a stab at it.

**Comment by philc** [comment]
Related: #23
