### ISSUE TITLE
Sheetkeys temporarily stops working on Google Chrome and needs to be reinstalled

### ISSUE THREAD

**Issue by santiyounger** [philc/sheetkeys#15]
Hey thanks for the awesome extension.

It had definitely been a game changer as a Vim user I'm addicted to vim shortcuts. Being able to use them in Google sheets is amazing.

---

This extension was working perfectly 2 days ago. But all of the sudden it tends to stop working and I have to reinstall it
I'm not sure if there's a Google Chrome update conflicting with things, but I'd love to fix it.

---

Would love to have this in the Google Web Store if possible, are there still plans to do this?

Thanks a lot

> Edit: Initially I stated that it wasn't working after reinstalling and reloading many times, but after trying it again it worked, but it's hard to predict when it will break again

### Specs:
Garuda Linux 
Google Chrome

**Comment by philc** [comment]
Hi Santi, thanks for the kind words. I use it every day too!

I'm using sheetkeys on a Mac. I updated my chrome this morning
to 91.0.4472.106 (Official Build) (x86_64) and Sheetkeys still works.

Are there any relevant log messages or errors on the javascript console?

**Comment by santiyounger** [comment]
Thanks for the quick reply, I got it working for now, but I do experience times when all of the sudden it stops working. 

If I experience it again I'll take a look into the inspector for errors and will let you know.

Just out of curiosity, because I want to recommend this extension to more people, does it still have plans to be in the Chrome "Web Store"?

Thanks for your hard work, this is one of my all time favorite extensions

**Comment by santiyounger** [comment]
unfortunately I keep experiencing this issue every few days.

Are there any plans to add this awesome extension to the Chrome Webstore?

Thanks

**Comment by philc** [comment]
Yes! I plan to within the next couple of months.

**Comment by santiyounger** [comment]
@philc that'd be amazing, thanks for the update! looking forward!

**Comment by philc** [comment]
@santiyounger I did finally get around to releasing this on the Chrome store [here](https://chrome.google.com/webstore/detail/sheetkeys/dnckajfoijllhbnfdhdklcfpckcbonhi), and there have been many improvements since. Cheers!

**Comment by santiyounger** [comment]
incredible @philc thank you!!
