### ISSUE TITLE
Switch between Sheets keybinding

### ISSUE THREAD

**Issue by Cretezy** [philc/sheetkeys#35]
Would be great to have a keymapping to switch between sheets (the tabs at the bottom).

Possibly `[t` and `]t` to match Vim behavior?

**Comment by philc** [comment]
Howdy -- this exists with capital `J` and `K`.

**Comment by philc** [comment]
I see this shortcut is not documented in the help dialog for some reason, which is a bug. I've filed that as #36. Thanks for reporting this!
