### ISSUE TITLE
`sheetkeys` in edge store outdated

### ISSUE THREAD

**Issue by kuntau** [philc/sheetkeys#55]
I was wondering why many shortcuts didn't work, while you have update to adapt the changes in Sheets in GitHub. Upon further checking, version in edge store still the old v0.4. 

Edge stores need some love yo.

Thank you!

P/S Is there any key to automatically stay in `insert mode` in the next cell after <kbd>enter</kbd> in currently editing cell like <kbd>ctrl+o</kbd>+<kbd>o</kbd> or <kbd>ctrl+o</kbd>+<kbd>O</kbd> in real vim

**Comment by philc** [comment]
Oh no, that's my mistake! I'll get a release out to the Edge store today.

Regarding ctrl-0 o, I've never really used that pattern in Vim, but it seems like a good application in the spreadsheet context. Feel free to file an issue with the idea and maybe someone will tackle it.

**Comment by philc** [comment]
I've submitted 0.5 to the Edge store and it's in review. It should go live in the next 1-2 days.
